### PR TITLE
fix: always quote objects property names

### LINKED ISSUE #30: JSON property names are strings and should be quoted
Property names are strings and these are surrounded by quotes.

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, 
> ...
> string
>   '"' characters '"'
https://www.json.org/json-en.html

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #30 

Screenshot 2024-09-02 at 10 08 40

### CODE REVIEW

File: src/DataRenderer.tsx [hunk 1]
```diff
@@ -17,7 +17,8 @@ export interface StyleProps {
   expandIcon: string;
   collapseIcon: string;
   collapsedContent: string;
-  noQuotesForStringValues: boolean;
+  noQuotesForStringValues?: boolean;
+  quotesForFieldNames?: boolean;
```
Comment (AndyOGo) [inline src/DataRenderer.tsx:21]: @AnyRoad 
I updated this PR to make field name quotes optional via `quotesForFieldNames` style config.

Comment (AnyRoad) [reply src/DataRenderer.tsx:21]: Thank you! 👍
